name: Build JAR file with Maven

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven
    - name: Build JAR file with Maven
      run: ./mvnw package -DskipTests
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v3
    - name: Upload JAR files 
      uses: actions/upload-artifact@v3
      with:
        name: Package
        path: target/*.jar