name: Deploy to Netlify

on:
  push:
    branches:
      - main
    paths:
      - src/main/webapp/**
jobs:
  build_and_deploy_job:
    name: Build and Deploy Job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build web artifacts
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: "npm"
    - name: Build react project 
      run: |
        npm ci
        npm run demo_build
    - name: Deploy to Netlify
      uses: netlify/actions/cli@master
      with:
        args: deploy --dir=src/main/resources/static --prod
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}